DELETE FROM mysql.user WHERE user='';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS '$MYSQL_USERNAME'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON `wordpress`.* TO '$MYSQL_USERNAME'@'%';
FLUSH PRIVILEGES;
